version: '3.9'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nova_senha
      MYSQL_DATABASE: course_restapi_udemy
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
  app:
    image: openjdk:17-jdk-slim
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/course_restapi_udemy?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: nova_senha
    volumes:
      - ./:/app
    working_dir: /app
    command: ["java", "-jar", "target/project-0.0.1-SNAPSHOT.jar"]