cors:
  originPatterns: http://localhost:3000,http://localhost:8080,http://localhost:4200,http://localhost:8888
file:
  upload-dir: /Users/iurypedrosa/Desktop/Mesa/Sistemas de Informação./Cursos/Back End/REST API/project
security:
  jwt:
    secret-key: 53cr37
    expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course_restapi_udemy?useSSL=false&serverTimezone=UTC
    username: root
    password: nova_senha
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      show_sql: true
      format_sql: true
servlet:
  multipart:
    enabled: true
    file-size-threshold: 2KB
    max-file-size: 200 MB
    max-request-size: 215MB
springdoc:
  paths-to-match:
  - /auth/**
  - /api/**/v1/**
  swagger-ui:
    use-root-path: true
flyway:
  repair: true

